In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import requests

In [32]:
import requests

url = "https://api.themoviedb.org/3/movie/now_playing?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI4OTJlOTAwNTM3MTQ0YWUzNGM0MzQxYjdkODI1NjU3YiIsIm5iZiI6MTcyNzk3MTI4Ni4yMTQ2NzYsInN1YiI6IjY2ZmViNTQ2NmZjNzRlNTc1NmY3ZGFlNSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.TocutSrVEprTPtfAz0fk6ryeGVz4mkyzQhac4d0Txg0"
}


response = requests.get(url, headers=headers)
response = response.json()

now = pd.DataFrame(response["results"])

In [33]:
import requests

url = "https://api.themoviedb.org/3/movie/popular?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI4OTJlOTAwNTM3MTQ0YWUzNGM0MzQxYjdkODI1NjU3YiIsIm5iZiI6MTcyNzk3MTI4Ni4yMTQ2NzYsInN1YiI6IjY2ZmViNTQ2NmZjNzRlNTc1NmY3ZGFlNSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.TocutSrVEprTPtfAz0fk6ryeGVz4mkyzQhac4d0Txg0"
}

response = requests.get(url, headers=headers)
response = response.json()

now1 = pd.DataFrame(response["results"])

In [34]:
import requests

url = "https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI4OTJlOTAwNTM3MTQ0YWUzNGM0MzQxYjdkODI1NjU3YiIsIm5iZiI6MTcyNzk3MTI4Ni4yMTQ2NzYsInN1YiI6IjY2ZmViNTQ2NmZjNzRlNTc1NmY3ZGFlNSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.TocutSrVEprTPtfAz0fk6ryeGVz4mkyzQhac4d0Txg0"
}

response = requests.get(url, headers=headers)
response = response.json()

now2 = pd.DataFrame(response["results"])

In [35]:
import requests

url = "https://api.themoviedb.org/3/movie/upcoming?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI4OTJlOTAwNTM3MTQ0YWUzNGM0MzQxYjdkODI1NjU3YiIsIm5iZiI6MTcyNzk3MTI4Ni4yMTQ2NzYsInN1YiI6IjY2ZmViNTQ2NmZjNzRlNTc1NmY3ZGFlNSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.TocutSrVEprTPtfAz0fk6ryeGVz4mkyzQhac4d0Txg0"
}

response = requests.get(url, headers=headers)
response = response.json()

now3 = pd.DataFrame(response["results"])

In [36]:
now.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/Asg2UUwipAdE87MxtJy7SQo08XI.jpg,"[28, 14, 27, 53, 80]",957452,en,The Crow,Soulmates Eric and Shelly are brutally murdere...,1403.514,/58QT4cPJ2u2TqWZkterDq9q4yxQ.jpg,2024-08-21,The Crow,False,5.400,459
1,False,/wh1IhMWkW7u5c5bkzSGFylF9G8r.jpg,"[28, 80, 53]",1215162,en,Kill 'em All 2,Phillip and Suzanne are retired from the spy g...,1201.354,/hgA5hN3NjNNSTXYOmAI6KNKOzbp.jpg,2024-09-24,Kill 'em All 2,False,7.186,51
2,False,/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg,"[878, 27]",933260,en,The Substance,A fading celebrity decides to use a black mark...,1131.940,/lqoMzCcZYEFK729d6qzt349fB4o.jpg,2024-09-07,The Substance,False,7.269,195
3,False,/zAqBIeO71BFL7bAtP5TFzVjVamy.jpg,"[10749, 18]",1079091,en,It Ends with Us,When a woman's first love suddenly reenters he...,1014.814,/cSMdFWmajaX4oUMLx7HEDI84GkP.jpg,2024-08-07,It Ends with Us,False,6.920,615
4,False,/A1dZ6faTjg0e6HYftBmEKujuXGQ.jpg,"[35, 14, 27]",917496,en,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...",861.066,/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg,2024-09-04,Beetlejuice Beetlejuice,False,7.156,764

In [37]:
now1.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/dvBCdCohwWbsP5qAaglOXagDMtk.jpg,"[28, 35, 878]",533535,en,Deadpool & Wolverine,A listless Wade Wilson toils away in civilian ...,6163.133,/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg,2024-07-24,Deadpool & Wolverine,False,7.800,3605
1,False,/lgkPzcOSnTvjeMnuFzozRO5HHw1.jpg,"[16, 10751, 35, 28]",519182,en,Despicable Me 4,"Gru and Lucy and their girls—Margo, Edith and ...",2244.623,/wWba3TaojhK7NdycRhoQpsG0FaH.jpg,2024-06-20,Despicable Me 4,False,7.200,1824
2,False,/Asg2UUwipAdE87MxtJy7SQo08XI.jpg,"[28, 14, 27, 53, 80]",957452,en,The Crow,Soulmates Eric and Shelly are brutally murdere...,1403.514,/58QT4cPJ2u2TqWZkterDq9q4yxQ.jpg,2024-08-21,The Crow,False,5.402,459
3,False,/p5ozvmdgsmbWe0H8Xk7Rc8SCwAB.jpg,"[16, 10751, 12, 35, 18]",1022789,en,Inside Out 2,Teenager Riley's mind headquarters is undergoi...,1220.104,/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg,2024-06-11,Inside Out 2,False,7.600,4032
4,False,/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg,"[878, 27]",933260,en,The Substance,A fading celebrity decides to use a black mark...,1131.940,/lqoMzCcZYEFK729d6qzt349fB4o.jpg,2024-09-07,The Substance,False,7.269,195

In [38]:
now2.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,136.210,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.706,26880
1,False,/tmU7GeKVybMWFButWEGl2M4GeiP.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",106.566,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.690,20397
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,88.012,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.575,12309
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,71.445,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.564,15717
4,False,/qqHQsStV6exghCM7zbObuYBiYxw.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,42.328,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.500,8539

In [39]:
now3.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg,"[878, 27]",933260,en,The Substance,A fading celebrity decides to use a black mark...,1131.940,/lqoMzCcZYEFK729d6qzt349fB4o.jpg,2024-09-07,The Substance,False,7.269,195
1,False,/reNf6GBzOe48l9WEnFOxXgW56Vg.jpg,"[18, 80, 53]",889737,en,Joker: Folie à Deux,"While struggling with his dual identity, Arthu...",850.848,/if8QiqCI7WAGImKcJCfzp6VTyKA.jpg,2024-10-01,Joker: Folie à Deux,False,6.481,80
2,False,/4zlOPT9CrtIX05bBIkYxNZsm5zN.jpg,"[16, 878, 10751]",1184918,en,The Wild Robot,"After a shipwreck, an intelligent robot called...",818.040,/hn4fOpFlbak5ruxkdrmdijs38Yl.jpg,2024-09-12,The Wild Robot,False,7.800,83
3,False,/tAwfoDyKiYa4KQdUp3DTMrEs4En.jpg,"[16, 878, 12, 10751]",698687,en,Transformers One,The untold origin story of Optimus Prime and M...,582.958,/qbkAqmmEIZfrCO8ZQAuIuVMlWoV.jpg,2024-09-11,Transformers One,False,7.347,98
4,False,/sjC29cgm4qZAnpOJQbYKCxDCcra.jpg,"[27, 878, 53]",1062215,en,Afraid,Curtis Pike and his family are selected to tes...,445.293,/gUREuXCnJLVHsvKXDH9fgIcfM6e.jpg,2024-08-28,Afraid,False,6.427,158

In [40]:
df = pd.concat([now, now1, now2, now3])

In [41]:
df.head()

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/Asg2UUwipAdE87MxtJy7SQo08XI.jpg,"[28, 14, 27, 53, 80]",957452,en,The Crow,Soulmates Eric and Shelly are brutally murdere...,1403.514,/58QT4cPJ2u2TqWZkterDq9q4yxQ.jpg,2024-08-21,The Crow,False,5.400,459
1,False,/wh1IhMWkW7u5c5bkzSGFylF9G8r.jpg,"[28, 80, 53]",1215162,en,Kill 'em All 2,Phillip and Suzanne are retired from the spy g...,1201.354,/hgA5hN3NjNNSTXYOmAI6KNKOzbp.jpg,2024-09-24,Kill 'em All 2,False,7.186,51
2,False,/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg,"[878, 27]",933260,en,The Substance,A fading celebrity decides to use a black mark...,1131.940,/lqoMzCcZYEFK729d6qzt349fB4o.jpg,2024-09-07,The Substance,False,7.269,195
3,False,/zAqBIeO71BFL7bAtP5TFzVjVamy.jpg,"[10749, 18]",1079091,en,It Ends with Us,When a woman's first love suddenly reenters he...,1014.814,/cSMdFWmajaX4oUMLx7HEDI84GkP.jpg,2024-08-07,It Ends with Us,False,6.920,615
4,False,/A1dZ6faTjg0e6HYftBmEKujuXGQ.jpg,"[35, 14, 27]",917496,en,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...",861.066,/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg,2024-09-04,Beetlejuice Beetlejuice,False,7.156,764

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 80 entries, 0 to 19
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              80 non-null     bool
 1   backdrop_path      80 non-null     object
 2   genre_ids          80 non-null     object
 3   id                 80 non-null     int64
 4   original_language  80 non-null     object
 5   original_title     80 non-null     object
 6   overview           80 non-null     object
 7   popularity         80 non-null     float64
 8   poster_path        80 non-null     object
 9   release_date       80 non-null     object
 10  title              80 non-null     object
 11  video              80 non-null     bool
 12  vote_average       80 non-null     float64
 13  vote_count         80 non-null     int64
dtypes: bool(2), float64(2), int64(2), object(8)
memory usage: 8.3+ KB

In [43]:
df.drop_duplicates(subset=['original_title'])

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/Asg2UUwipAdE87MxtJy7SQo08XI.jpg,"[28, 14, 27, 53, 80]",957452,en,The Crow,Soulmates Eric and Shelly are brutally murdere...,1403.514,/58QT4cPJ2u2TqWZkterDq9q4yxQ.jpg,2024-08-21,The Crow,False,5.400,459
1,False,/wh1IhMWkW7u5c5bkzSGFylF9G8r.jpg,"[28, 80, 53]",1215162,en,Kill 'em All 2,Phillip and Suzanne are retired from the spy g...,1201.354,/hgA5hN3NjNNSTXYOmAI6KNKOzbp.jpg,2024-09-24,Kill 'em All 2,False,7.186,51
2,False,/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg,"[878, 27]",933260,en,The Substance,A fading celebrity decides to use a black mark...,1131.940,/lqoMzCcZYEFK729d6qzt349fB4o.jpg,2024-09-07,The Substance,False,7.269,195
3,False,/zAqBIeO71BFL7bAtP5TFzVjVamy.jpg,"[10749, 18]",1079091,en,It Ends with Us,When a woman's first love suddenly reenters he...,1014.814,/cSMdFWmajaX4oUMLx7HEDI84GkP.jpg,2024-08-07,It Ends with Us,False,6.920,615
4,False,/A1dZ6faTjg0e6HYftBmEKujuXGQ.jpg,"[35, 14, 27]",917496,en,Beetlejuice Beetlejuice,"After a family tragedy, three generations of t...",861.066,/kKgQzkUCnQmeTPkyIwHly2t6ZFI.jpg,2024-09-04,Beetlejuice Beetlejuice,False,7.156,764
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15,False,/vJk9DOLgP23jO5mBnPHE93MFgYu.jpg,"[12, 10751, 14, 35]",826510,en,Harold and the Purple Crayon,"Inside of his book, adventurous Harold can mak...",193.794,/dEsuQOZwdaFAVL26RjgjwGl9j7m.jpg,2024-07-31,Harold and the Purple Crayon,False,7.100,144
16,False,/obKmfNexgL4ZP5cAmzdL4KbHHYX.jpg,"[12, 14]",673,en,Harry Potter and the Prisoner of Azkaban,Year three at Hogwarts means new fun and chall...,162.345,/aWxwnYoe8p2d2fcxOqtvAtJ72Rw.jpg,2004-05-31,Harry Potter and the Prisoner of Azkaban,False,8.019,21342
17,False,/AfXoko90cVuDz1KuVamkSMRKBWy.jpg,"[35, 18]",1125073,en,Between the Temples,A grief-stricken cantor in a crisis of faith f...,147.951,/iOVe3xoJDIdMMYvCy18a4TlDIOK.jpg,2024-08-22,Between the Temples,False,5.100,7
18,False,/xlkclSE4aq7r3JsFIJRgs21zUew.jpg,"[27, 53]",1034541,en,Terrifier 3,After surviving Art the Clown's Halloween mass...,136.818,/fD4ZNG3r6qWH4DBXw2CHonm2yHK.jpg,2024-10-09,Terrifier 3,False,0.000,0
19,False,/b6DU3kBmicMbpNvvkqf1cHaceMF.jpg,"[27, 18]",814889,en,Never Let Go,As an evil takes over the world beyond their f...,113.360,/3EpZ2ksjijmdr8BhISP03PYzNFW.jpg,2024-09-18,Never Let Go,False,5.910,39

In [47]:
for i in df["id"]:
def get_revenue_budget(df)

url = "https://api.themoviedb.org/3/movie/"+str(i)+"?language=en-US"

data = {
    "budget":
    "revenue":
}

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI4OTJlOTAwNTM3MTQ0YWUzNGM0MzQxYjdkODI1NjU3YiIsIm5iZiI6MTcyNzk3MTI4Ni4yMTQ2NzYsInN1YiI6IjY2ZmViNTQ2NmZjNzRlNTc1NmY3ZGFlNSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.TocutSrVEprTPtfAz0fk6ryeGVz4mkyzQhac4d0Txg0"
}

response = requests.get(url, headers=headers)
response = response.json()
data["budget"].append(response["budget"])
data["revenue"].append(response["revenue"])
break
return pd.DataFrame(data)

IndentationError: expected an indented block (181300868.py, line 2)